### ISSUE TITLE
Update port

### ISSUE THREAD

**Issue by mojca** [macports/upt-macports#14]
The `py-upt-macports` port is currently generating defunct packages, including #11 and printing empty licence name (https://github.com/macports/macports-ports/pull/4489).

Can you please update the `Portfile`?

@rajdeepbharati

**Comment by reneeotten** [comment]
the Portfile should certainly be updated, but it will (I think, after only a quick look) not solve the issue for the empty license field in ```py-buildbot-worker```. For some reason (@Korusuke @Steap ?), ```self.upt_pkg.licenses``` returns an empty list and that situation isn't handled yet in the MacPorts backend.

**Comment by Steap** [comment]
Sometimes upt fails to guess the licence, and may return an empty list. This should be handled in the backend.

**Comment by reneeotten** [comment]
> Sometimes upt fails to guess the licence, and may return an empty list. This should be handled in the backend.

Okay, thanks! @Korusuke I would suggest to take care of this first (including adding tests) and then after that is merged you can update the Portfile.

**Comment by mojca** [comment]
I would suggest to:
* check whether something can be improved in packaging of that particular pypi package
* figure out if the backend could guess the licence for that package in existing state
* even if the backend returns an empty set, the frontend should still use `unknown`

**Comment by rajgoesout** [comment]
> Can you please update the Portfile?

Updated.

**Comment by Korusuke** [comment]
> * check whether something can be improved in packaging of that particular pypi package

I compared `buildbot-worker` and `upt` to find out what was going wrong.
In upt-pypi while detecting the license if the license falls under the "not actual license" category then even if the license attribute is written in classifiers, it tries to find a "LICENSE" or "LICENSE.txt" file which is missing for `buildbot-worker` and so it fails to detect the license.

So as for improving this goes @Steap would be able to decide here, that if the license is there in the classifiers list given by pypi then should we just get it from there? even if its not an "actual licence".
I suppose @Steap  would have done this for some reason which I am not sure what it is.

> *even if the backend returns an empty set, the frontend should still use unknown

I have done this in PR #18

**Comment by mojca** [comment]
> > Can you please update the Portfile?
> 
> Updated.

Just to clarify: this was a request for @Korusuke to update the `py-upt-macports` port in MacPorts.

**Comment by mojca** [comment]
I just wanted to add that in case you believe that the various `buildbot` packages could be improved on pypi, we could ask upstream to improve them for the next version (the authors are even gsoc mentors for MacPorts this year, so it shouldn't be a problem).

**Comment by Steap** [comment]
About buildbot packaging, two things:

1) They use the "license" field (see https://github.com/buildbot/buildbot/blob/b251035aca12be84397d59394403f9a15dd17a8b/master/setup.py#L148) but this field should only be used for licenses that do not have a dedicated classifier

2) They use a classifier that is not really a license (see https://github.com/buildbot/buildbot/blob/b251035aca12be84397d59394403f9a15dd17a8b/master/setup.py#L154). They should probably use "License :: OSI Approved :: GNU General Public License v2 (GPLv2)" or "License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)" for instance.

**Comment by mojca** [comment]
@tardyp, @p12tic: could you please check the licences of your buildbot packages in the light of what @Steap is suggesting?

**Comment by mojca** [comment]
With respect to `py-buildbot-www`: it doesn't seem to return any dependencies, but the build fails with
```
Please install buildbot, buildbot_pkg, and mock modules in order to install that package, or use the pre-build .whl modules available on pypi
```
I guess that's another thing that needs to be addressed by the buildbot developers when packaging pypi?

**Comment by mojca** [comment]
Can one of you please open an issue for the buildbot explaining what changes are expected, so that upt would automatically work correctly?

**Comment by Steap** [comment]
I opened https://github.com/buildbot/buildbot/pull/4803 to fix the license issue. I will open another request for the requirements later.
