### ISSUE TITLE
Perl Build-Dependencies

### ISSUE THREAD

**Issue by Korusuke** [macports/upt-macports#22]
As currently, upt-cpan ignores build dependency they are not available to the backend.

Now my doubt is, do we need "develop" and "configure" dependencies?

As I see in the Port B-utils the build dependency is written in the original portfile is actually from "configure" in the json and the "build" ones from the json are not written.

My view would be to write all three under build dependency?
What are your views on this? @reneeotten @mojca 

Also @Steap, should I push a PR for the same to upt-cpan once this is decided as the only change would be to change the mapping of `phases_to_upt_phases` and change the if statement.

**Comment by Steap** [comment]
Please report a bug against upt-cpan, giving a detailed example (select a package in particular to prove your point) and what changes you'd like to see.

**Comment by reneeotten** [comment]
I cannot easily a few minutes of Google-ing) find documentation stating what the exact difference between the ```build```, ```configure``` , and ```develop``` dependencies are... I *think* you are right that the "configure" ones should be added under the build-dependencies, but am not sure about the "develop" ones.... Perhaps @mojca or @dbevans can point us in the right direction here?

**Comment by mojca** [comment]
I would need to check some individual ports. My first impression would be that `build` and `configure` should both be added to `depends_build`. What `develop` dependencies are ... no idea. These could be dependencies needed by developers of the package (stuff like `autotools`, just in the perl context), but we need to take a look at some packages declaring such dependencies first and then see what they are. Also, perl's IRC channel might be a much more reliable source of information than me.

**Comment by reneeotten** [comment]
okay, I looked a bit more and -of course- the information is available on the web ;) The description of the [metadata](metacpan.org/pod/CPAN::Meta::Spec) and specifically the [part about dependencies/types](https://metacpan.org/pod/CPAN::Meta::Spec#PREREQUISITES). [Please do look at this documentation also in the light of the ```perl5.setup``` line, the other remaining piece for getting ```upt``` to generate Perl portfiles correctly].

From that information I'd say we do add the ```configure``` and ```build``` dependencies to ```depends_build``` and do not add the ```develop``` dependencies.

I would prefer the ```upt-cpan``` frontend though to process all the dependency types instead of [ignoring](https://framagit.org/upt/upt-cpan/blob/master/upt_cpan/upt_cpan.py#L71) them so that all metadata on dependencies is available; the backend can then decide which ones to use.

@Korusuke please submit a PR to the ```upt-cpan``` repository so that @Steap can review it.

**Comment by Korusuke** [comment]
> I would prefer the `upt-cpan` frontend though to process all the dependency types instead of [ignoring](https://framagit.org/upt/upt-cpan/blob/master/upt_cpan/upt_cpan.py#L71) them so that all metadata on dependencies is available; the backend can then decide which ones to use.
>
I have already done this yesterday, but instead of a PR I created an issue as previously suggested by @Steap , I don't have any issue with submitting a PR too as I have already done the changes in my local copy :)

> @Korusuke please submit a PR to the `upt-cpan` repository so that @Steap can review it.

Edit: [Link of the issue](https://framagit.org/upt/upt-cpan/issues/1)

**Comment by Steap** [comment]
From what I understand, 'config' would be something like the autotools and 'build' would be libfoo, required to compile the package. 

Don't worry about the PR, I can do it myself :) You're already doing a lot of good work on upt-macports.

**Comment by mojca** [comment]
`autotools` is a bad example as it's usually not needed. What is needed is for example `cmake`, `pkg-config` etc.
`libfoo` is another bad example of a build dependency as libraries (like `libpng`) are typically needed all the time, both during build and when running the program.
(Not that I fully understand what these dependencies are.)

**Comment by Steap** [comment]
Yeah I said "autotools" because I was htinking of C. I think "config" is for Perl tools like autotools in C, setuptools in Python, etc. And of course, cmake, pkg-config :)

I think both config and build dependencies could be considered "build" dependencies, right?

**Comment by reneeotten** [comment]
> I think both config and build dependencies could be considered "build" dependencies, right?

Agreed, see the link about the different types I posted above.

@Korusuke sorry, I missed that you opened an Issue already!

**Comment by mojca** [comment]
(Yes, I was also thinking of C. But there's a huge difference in that `autotools`, `automake` etc. would usually be run by the package author prior to making a release, while the user would only run `./configure`. This is why I said it was probably not the best example, even if we forget about the perl world.)

**Comment by reneeotten** [comment]
this has been addressed with the [release](https://framagit.org/upt/upt-cpan/blob/master/CHANGELOG) of ```upt-cpan``` version 0.5 and the merge of PR #19
