### ISSUE TITLE
Clean up template code

### ISSUE THREAD

**Issue by Steap** [macports/upt-macports#31]
In {ruby,python,perl}.Portfile, the same kind of code can be found:

```jinja2
    {%- if pkg.upt_pkg.requirements.run|length > 0 %}
    depends_lib-append \
                    {% for i in pkg.upt_pkg.requirements.run|sort(attribute='name') %}
                    port:py${python.version}-{{i.name}}{% if not loop.last %} \
                    {% endif %}
                    {% endfor %}
    {% endif %}
```

The main difference between the templates is the way the dependency is displayed.

1) We could create a Jinja filter (see for instance what is done in upt-openbsd: https://framagit.org/upt/upt-openbsd/blob/master/upt_openbsd/upt_openbsd.py#L79). The filter could easily be tested in the unit tests.

2) Maybe create a macro that prints the dependencies? See https://framagit.org/upt/upt-openbsd/blob/master/upt_openbsd/templates/base.mk#L1

This would reduce the amount of code needed in the templates, and improve readability.

**Comment by reneeotten** [comment]
closed with 5ce0be762c467f4361897cfb1d3493e2586713ef
