### ISSUE TITLE
Do not scan the frontend twice

### ISSUE THREAD

**Issue by Steap** [macports/upt-macports#41]
In _create_output_directories, we "scan" the frontend:

```python
    upt2macports = {
        'cpan': 'perl',
        'pypi': 'python',
        'rubygems': 'ruby',
    }
``` 

We already do that once in MacportsBackend.create_package(). We should only do it once.

**Comment by Korusuke** [comment]
We can do something like add a variable `category = 'python'` to MacPortsPythonPackage() and use that directly in place of `port_category`
