### ISSUE TITLE
Tests: use coverage

### ISSUE THREAD

**Issue by Steap** [macports/upt-macports#8]
It would be nice to use "coverage" in the tests. Upt does it (see https://framagit.org/upt/upt/commit/3dfc1b4c7b3a163212754538b973503263759b6c) and it helps detect which parts of the code are never executed when running the tests.

**Comment by reneeotten** [comment]
Sure, that never hurts! 

In the same PR to add this, let's also fix the configuration for the Azure pipelines that Rainer enabled. Configuration file is ```azure-pipelines.yml``` and the documentation is [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/python?view=azure-devops).
